"""create bottle_tracking table

Revision ID: 54f33ef7f01b
Revises: 
Create Date: 2025-08-13 13:36:14.650570

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '54f33ef7f01b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bottle_tracking',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('bottle_type', sa.String(length=20), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('carbon_footprint', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bottle_tracking_bottle_type'), 'bottle_tracking', ['bottle_type'], unique=False)
    op.create_index(op.f('ix_bottle_tracking_created_at'), 'bottle_tracking', ['created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_bottle_tracking_created_at'), table_name='bottle_tracking')
    op.drop_index(op.f('ix_bottle_tracking_bottle_type'), table_name='bottle_tracking')
    op.drop_table('bottle_tracking')
    # ### end Alembic commands ###
