"""user table updated

Revision ID: 604a583a539c
Revises: fedabc670b26
Create Date: 2025-08-19 13:54:19.851394

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '604a583a539c'
down_revision: Union[str, Sequence[str], None] = 'fedabc670b26'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('job_name', sa.String(length=50), nullable=True))
    op.drop_constraint(op.f('FK__users__job_id__5FB337D6'), 'users', type_='foreignkey')
    op.drop_column('users', 'job_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('job_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('FK__users__job_id__5FB337D6'), 'users', 'job_title', ['job_id'], ['id'])
    op.drop_column('users', 'job_name')
    # ### end Alembic commands ###
