"""add password table v2

Revision ID: 6e79cef72d22
Revises: 604a583a539c
Create Date: 2025-08-19 14:00:44.455134

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6e79cef72d22'
down_revision: Union[str, Sequence[str], None] = '604a583a539c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('job_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'users', 'job_title', ['job_id'], ['id'])
    op.drop_column('users', 'job_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('job_name', sa.VARCHAR(length=50, collation='Turkish_CI_AS'), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'job_id')
    # ### end Alembic commands ###
