"""create initial tables

Revision ID: c1ae1c5ef35c
Revises: 54f33ef7f01b
Create Date: 2025-08-18 16:31:13.858135

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c1ae1c5ef35c'
down_revision: Union[str, Sequence[str], None] = '54f33ef7f01b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('job_title',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('job_name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('job_name')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_name', sa.String(length=50), nullable=False),
    sa.Column('user_surname', sa.String(length=50), nullable=False),
    sa.Column('user_email', sa.String(length=100), nullable=False),
    sa.Column('user_phone', sa.String(length=20), nullable=True),
    sa.Column('job_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['job_id'], ['job_title.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_user_email'), 'users', ['user_email'], unique=True)
    op.create_table('user_address',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('city', sa.String(length=50), nullable=False),
    sa.Column('district', sa.String(length=50), nullable=False),
    sa.Column('neighborhood', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('bottle_tracking', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_bottle_tracking_bottle_type'), 'bottle_tracking', ['bottle_type'], unique=False)
    op.create_index(op.f('ix_bottle_tracking_created_at'), 'bottle_tracking', ['created_at'], unique=False)
    op.create_foreign_key(None, 'bottle_tracking', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'bottle_tracking', type_='foreignkey')
    op.drop_index(op.f('ix_bottle_tracking_created_at'), table_name='bottle_tracking')
    op.drop_index(op.f('ix_bottle_tracking_bottle_type'), table_name='bottle_tracking')
    op.drop_column('bottle_tracking', 'user_id')
    op.drop_table('user_address')
    op.drop_index(op.f('ix_users_user_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('job_title')
    # ### end Alembic commands ###
